### ISSUE TITLE
MS SQL Support

### ISSUE THREAD

**Issue by Jpatel2408** [CoverGenius/django-reactive#20]
* Django-reactive version:
* Django version:
* Python version:3.9
* Operating System: Windows 10

### Description

I am trying to use Django-reactive in my project. I am using Microsoft SQL server 2019. but it gives an error because of the database. 

### What I Did

```
python manage.py migrate.
 'django.db.utils.ProgrammingError: ('42000', '[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Column, parameter, or variable #2: Cannot find data type jsonb. (2715) (SQLExecDirectW)')'. because jsonfield come from postgres.
```

**Comment by tyomo4ka** [comment]
Hi @Jpatel2408 

Thanks for opening this issue. 

This project was never meant to be working with MS SQL. However, you can use code from this project and extend the MS SQL JSON field type implementation to support React JSON Schema Form features in the same way how it works here.

Please, let me know if you end up writing an implementation for MS SQL. I will add a cross-link to this project.
